### ISSUE TITLE
[Bug]: Nora Settings Link

### ISSUE THREAD

**Issue by dominichayesferen** [Floorp-Projects/Floorp-12#22]
### Pre-Submission Checklist

- [x] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [x] I am using the latest supported version of the browser.
- [x] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [x] I have tried clearing the browser cache and cookies.
- [x] I have checked with a new profile and the issue still occurs.
- [x] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [x] I have included relevant screenshots or console outputs.
- [x] I have checked that this problem is not occurring in the latest version of Firefox.
- [x] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The link to Floorp (Noraneko) Settings in Settings (Firefox):
- Has a placeholder label - "Nora Settings Link"
- Behaves somewhat like a category, becoming selected once clicked on, rather than a link

### Reproduction Steps

1. Go to Settings (Firefox)
2. See and click Nora

### Expected Behavior

- The label saying "Floorp Settings", or "More Settings"?
- The option not being 'selected' upon being used

### Actual Behavior

- "Nora Settings Link", of course
- The option becomes the selected category, visually, once clicked

### Screenshots

![Image](https://github.com/user-attachments/assets/4a2da591-b0f4-4ec5-a4fb-dda694c9aa5a)

![Image](https://github.com/user-attachments/assets/8433a2f3-c31c-4e0e-b20d-44f594b94bf5)

### Browser Version

tag:beta

### Operating System

Feren OS 2025.03 (Ubuntu 22.04)

**Comment by TheChilledBuffalo** [comment]
This issue has been fixed in the latest dev build. So I think this can be closed.

![Image](https://github.com/user-attachments/assets/fa541e6d-ea42-4419-8b0f-ddd05487ac71)

**Comment by dominichayesferen** [comment]
The selection issue still exists, just now partially 
![Image](https://github.com/user-attachments/assets/feb82462-96d2-4f85-8853-fe7b1b70a044)

**Comment by CutterKnife** [comment]
Well, it's not an important issue IMO.

**Comment by Walkmana-25** [comment]
We have confirmed that it has been fixed.
