### ISSUE TITLE
[Bug] Auto-Update Fails to Install Updates

### ISSUE THREAD

**Issue by moriel5** [Floorp-Projects/Floorp-12#58]
OS: Linux 6.12.21 (Solus 4.7)
Desktop Environment: Budgie 10.9.2
Floorp 12 version: 0.1.21
Floorp build variant: Portable (self-packaged, and eventually official inclusion in Solus repositories planned)

It appears that the built-in autoupdate function in Floorp 12 is broken, as while it downloads just fine, it immediately fails to install upon finishing downloading, without any delay.

I presume that this is probably due to how early in the development cycle this is, and most developers are in any case either self-compiling or using the portable build (with Linux packagers simply compiling and packaging), so perhaps the manifest and/or the autoupdate mechanism aren't properly implemented yet, however I am print this out nevertheless.

**Comment by the51stater** [comment]
The in-app auto update does not work in Linux. Even with the Snap software package manager, you need to close the app to let the system do the auto update for the app.
That is, in Linux, the in-app update feature needs to be removed because it's useless.

**Comment by moriel5** [comment]
It does, and with no issues whatsoever.

**Comment by Suncatcher** [comment]
Looks like it is broken not only in Linux, for me this text is showed forever and downloads never started

![Image](https://github.com/user-attachments/assets/6129f823-8a72-4115-a550-dcf0c2cb9c17)

I'm on Windows 11 Pro

**Comment by surapunoyousei** [comment]
Fixed

**Comment by moriel5** [comment]
The last update, a few hours ago, still failed for me, however I shall return with a definite answer after the next update.

**Comment by surapunoyousei** [comment]
The old binary can no longer be updated, so please replace the binary manually. After that, automatic updates will work

**Comment by moriel5** [comment]
By the way, I only just found out about there being an official "portable" version (V1 and V2), so to clarify, on Linux and Unix, almost everything is portable, so when there is a "portable" version on those platforms, usually it just means it is compiled, but not packaged, regardless of whether it is "portable" in the "PortableApps" sense.

**Comment by moriel5** [comment]
The update worked... sort of.
Instead of outright failing, it installed the update and let me restart Floorp... only for it to crash.

When running ./floorp, ./floorp-bin, or ./updater from the terminal, it turned out that libmozsqlite3.so was missing.

Since manually replacing the files worked just fine, was this a new dependency that was missing in the .mar update file, or was there an issue unpacking it, or perhaps donating completely different?

**Comment by moriel5** [comment]
Update: With the newest update from 4 hours ago (I only got around to installing it now), same results, however I took a closer look.

The error was specifically with `updater`, `floorp` simply forwarded to `updater`, and libmozsqlite3.so was present, which means that `updater` seems to not be able to find libmozsqlite3.so.
